# -*- coding: utf-8 -*-
"""A.1 ( Part A )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAO7QUiWxwza43oIrQsd3dciovHqs5Ue
"""

class SocialMediaPost:
    def __init__(self, datetime, post_content, author):
        self.datetime = datetime
        self.post_content = post_content
        self.author = author

class SocialMediaManager:
    def __init__(self):
        self.posts = {}

    def add_post(self, post):
        # The datetime of the post serves as a unique key
        self.posts[post.datetime] = post

    def retrieve_post(self, datetime):
        # Retrieve a post in O(1) time using the datetime key
        if datetime in self.posts:
            return self.posts[datetime]
        else:
            return "There is no post found for the date and time provided"

    def display_post_details(self, datetime):
        post = self.retrieve_post(datetime)
        if post != "There is no post found for the date and time provided":
            print(f"Post Content: {post.post_content}")
            print(f"Author: {post.author}")
        else:
            print(post)

# Example Usage
post1 = SocialMediaPost("2024-04-19T08:00:00", "Good Morning Professor Drew!", "Lionel Messi")
post2 = SocialMediaPost("2024-03-19T08:00:00", "Nice Weather!", "Khalifa Alshehhi")
post3 = SocialMediaPost("2024-02-19T08:00:00", "How are you today?", "Undertaker")

manager = SocialMediaManager()
manager.add_post(post1)
manager.display_post_details("2024-04-19T08:00:00")

manager = SocialMediaManager()
manager.add_post(post3)
manager.display_post_details("2024-02-19T08:00:00")

manager = SocialMediaManager()
manager.add_post(post2)
manager.display_post_details("2004-09-19T09:00:00")