# -*- coding: utf-8 -*-
"""A.3 ( Part A )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYKIdntF4jM7cHQrTjOchjWb9Q-axssv
"""

import heapq

class SocialMediaPost:
    def __init__(self, post_content, author, views):
        self.post_content = post_content
        self.author = author
        self.views = views
        # The heap will store tuples, and we use negative views for max-heap behavior
        self.heap_node = (-self.views, self.post_content, self.author)

class PostHeap:
    def __init__(self):
        self.heap = []

    def add_post(self, post):
        # Insert the post into the heap
        heapq.heappush(self.heap, post.heap_node)

    def get_top_post(self):
        # Return the post with the maximum views
        if self.heap:
            top_post = heapq.heappop(self.heap)
            # Convert back to positive views
            return (-top_post[0], top_post[1], top_post[2])
        else:
            return "No posts available"

    def display_top_post(self):
        top_posts = []
        while self.heap:
            top_post = self.get_top_post()
            top_posts.append(top_post)
            if self.heap and self.heap[0][0] != top_post[0]:
                break
        if top_posts:
            for post in top_posts:
                print(f"Views: {post[0]}, Content: {post[1]}, Author: {post[2]}")
        else:
            print("No posts available")

# Example Usage
heap = PostHeap()
post1 = SocialMediaPost("What A Goal!!", "Pep", 343500)
post2 = SocialMediaPost("How to make the perfect pizza", "Margot", 134750)
post3 = SocialMediaPost("Look at the food!", "Simba", 68732)
post4 = SocialMediaPost("Do you love the snow?", "Elsa", 297873)

heap.add_post(post1)
heap.add_post(post2)
heap.add_post(post3)
heap.add_post(post4)

heap.display_top_post()

heap = PostHeap()
post11 = SocialMediaPost("What A Goal!!", "Pep", 500000)
post22 = SocialMediaPost("How to make the perfect pizza", "Margot", 134750)
post33 = SocialMediaPost("Look at the food!", "Simba", 68732)
post44 = SocialMediaPost("Do you love the snow?", "Elsa", 500000)

heap.add_post(post11)
heap.add_post(post22)
heap.add_post(post33)
heap.add_post(post44)

heap.display_top_post()